version: '3'

services:
  openvpn:
    build:
      context: .
      dockerfile: Dockerfile.openvpn
    image: openvpn:local
    command: /etc/openvpn/setup/configure.sh
    cap_add:
      - NET_ADMIN
    ports:
      - 7777:1194
    volumes:
      - ./easyrsa:/etc/openvpn/easyrsa
      - ./ccd:/etc/openvpn/ccd
  openvpn-admin:
    build:
      context: .
    image: openvpn-admin:local
    command: /app/openvpn-admin --debug --ovpn.network="172.16.100.0/22" --mgmt.host="openvpn"
    ports:
      - 8080:8080
    volumes:
      - ./easyrsa:/mnt/easyrsa
      - ./ccd:/mnt/ccd