name: Build and publish to Docker Hub (releases only)
on: 
  release:
    types: [created]
    
jobs:
  build:
    name: build latest images for relase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push openvpn image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: flant/openvpn-admin
          tags: openvpn-latest
          dockerfile:  Dockerfile.openvpn
      - name: Push openvpn-admin image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: flant/openvpn-admin
          tags: latest
          dockerfile: Dockerfile
