name: Build and publish to Docker Hub (releases only)
on: 
  release:
    types: [created]
    
jobs:
  build:
    name: Converge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Push openvpn image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          tags: flant/openvpn-admin:openvpn-latest
          context: .
          file:  Dockerfile.openvpn
          push: true
      - name: Push openvpn-admin image to Docker Hub
        uses: docker/build-push-action@v1
        with:
          tags: flant/openvpn-admin:latest
          file: Dockerfile
          context: .
          push: true
